### ISSUE TITLE
Where can I download the videos

### ISSUE THREAD

**Issue by jdsannchao** [JUNJIE99/MLVU#2]

**Comment by JUNJIE99** [comment]
Hi, you can obtain the video data through the following links:

- For the development set, please visit [MLVU Dev Set](https://huggingface.co/datasets/MLVU/MVLU).
- For the test set, please visit [MLVU Test Set](https://huggingface.co/datasets/MLVU/MLVU_Test).

**Comment by jdsannchao** [comment]
Thx!
