### ISSUE TITLE
Empty strings in the dev annotations

### ISSUE THREAD

**Issue by Becomebright** [JUNJIE99/MLVU#3]
Hi,

I've noticed some empty strings in the dev annotations. For instance, in `7_topic_reasoning.json`:

```
{
    "video": "movie101_89.mp4",
    "duration": 677,
    "question": "",
    "candidates": [
        "",
        "",
        "",
        ""
    ],
    "answer": "",
    "question_type": "topic_reasoning"
}
```

Could you please confirm if these are annotation errors? Thanks!

**Comment by JUNJIE99** [comment]
We have corrected and updated the relevant annotations. 

Thank you for pointing out the oversight.
