### ISSUE TITLE
Leaderboard mismatch

### ISSUE THREAD

**Issue by ssantos97** [JUNJIE99/MLVU#5]
Hi, 

Why are the results in the mini-leaderboard and full leaderboard as well as paper table different for the same methods?

**Comment by JUNJIE99** [comment]
Hello, the mini-leaderboard on the GitHub page differs from the full leaderboard because the mini-leaderboard reports results on the MLVU-dev set, while the full leaderboard reports results on the MLVU-Test set. In our current paper version, we only report results on the MLVU-dev set.
