### ISSUE TITLE
Data details

### ISSUE THREAD

**Issue by spidercatfly** [JUNJIE99/MLVU#6]
Hi all:

Thanks for your excellent benchmark dataset!

Do the videos in the dataset have complete source video information? For example, the original complete documentary corresponding to the documentary excerpt? Will there be multiple questions coming from the same complete video?

If so, how can I find the original complete video through the current dataset content?

Thanks in advance:)

**Comment by JUNJIE99** [comment]
Hi,

Thank you for your interest in our work.

We will not be disclosing the source of the original videos.

A small portion of the videos may come from the same source. However, all the questions are independent and can be answered based on the provided videos.

Thank you for your understanding.

**Comment by spidercatfly** [comment]
Got it.
Thanks.
